apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: first-app

  ports:
    - name: first-app
      protocol: TCP
      port: 80
      targetPort: 80 #The port to which your application is listening on

  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app
  labels:
    app: first-app
spec:
  selector:
    matchLabels:
      app: first-app
      tier: backend
  replicas: 1

  template:
    metadata:
      labels:
        app: first-app
        tier: backend
    spec:
      containers:
        - name: first-app
          image: felixayange/first-app:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            initialDelaySeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
