apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: first-app

  ports:
    - name: first-app
      protocol: TCP
      port: 80
      targetPort: 80 #The port to which your application is listening on

  type: LoadBalancer
